### ISSUE TITLE
Custom roles not saving abilities

### ISSUE THREAD

**Issue by Mike-Morris** [madoublet/respond#250]
Trying to make use of a custom user role, i've found that the abilities for a user are not being saved at all IF the abilities are being applied to "All" rather than a specific page type. 

Result being that users of that custom role have no abilities and cannot login to the CMS.

**Comment by MikeKTT** [comment]
Further to this, using individual page types to set privileges including edit and publish for a user role, users with edit/publish "in app" privileges still cannot log into the CMS... (User does not have admin privileges error thrown to the console.)

**Comment by madoublet** [comment]
This should be fixed now in the Respond 4.5 branch.

**Comment by ebomcke** [comment]
This issue is still present in Respond 4.6, there's an issue with a variable name in the getPrivileges method (canView should be renamed to canDo).

**Comment by msmithehi** [comment]
Wow!  Thanks.  This does fix the issue.  Saved me a lot of time hunting that down.  I will push an update to 4.8.

**Comment by madoublet** [comment]
This looks like it is fixed now.
