### ISSUE TITLE
Unable to scroll to add new image on gallery

### ISSUE THREAD

**Issue by a6smile** [madoublet/respond#476]
unable to scroll the image list on gallery to add more pictures. create new gallery are also same issue faced.

**Comment by madoublet** [comment]
Fixed in RC2. Now in production.  Thank you!

**Comment by simple-designs** [comment]
I just updated my Zip installation on DigitalOcean and I am still seeing this issue.

![screen shot 2016-11-14 at 9 00 02 pm](https://cloud.githubusercontent.com/assets/8508928/20291664/64a53332-aaad-11e6-8a5d-ac5ddf1e463d.png)
